# Generated by Django 4.1.2 on 2022-10-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_in', models.CharField(max_length=20, null=True)),
                ('cur_out', models.CharField(max_length=20, null=True)),
                ('amount', models.FloatField(null=True)),
                ('res', models.DecimalField(decimal_places=2, max_digits=70, null=True)),
                ('answer', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='EuroRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=20, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('url', models.URLField()),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
